name: Action Practice

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      
      - name: Run sync_qx.py
        run: python3 ./sync_qx.py
      
      - name: Commit and Push
        env: 
         GIT_NAME: ${{ secrets.GIT_NAME }}
         GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --local user.name "$GIT_NAME"
          git config --local user.email "$GIT_EMAIL"
          git add .
          git diff --staged --quiet || git commit -m "Github action update at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
