name: Sync to GitLab

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/ironicone/Outside.git"
          destination_repo: "https://gitlab.com/ironicone/Outside.git"
          destination_branch: "main"
          source_branch: "main"
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}